//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2013-03-13 14:16:04 by App
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace Apps.Models.Sys
{

    public partial class SysUserConfigModel
    {

        [Display(Name = "ID")]
        public override string Id { get; set; }

        [Display(Name = "名称")]
        public override string Name { get; set; }

        [Display(Name = "值")]
        public override string Value { get; set; }

        [Display(Name = "类型")]
        public override string Type { get; set; }

        [Display(Name = "状态")]
        public override bool? State { get; set; }

        [Display(Name = "用户")]
        public override string UserId { get; set; }



    }
}

