//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flow_Step
    {
        public Flow_Step()
        {
            this.Flow_StepRule = new HashSet<Flow_StepRule>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public int Sort { get; set; }
        public string FormId { get; set; }
        public int FlowRule { get; set; }
        public bool IsCustom { get; set; }
        public bool IsAllCheck { get; set; }
        public string Execution { get; set; }
        public bool CompulsoryOver { get; set; }
        public bool IsEditAttr { get; set; }
    
        public virtual Flow_Form Flow_Form { get; set; }
        public virtual ICollection<Flow_StepRule> Flow_StepRule { get; set; }
    }
}
