//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flow_FormContentStepCheck
    {
        public Flow_FormContentStepCheck()
        {
            this.Flow_FormContentStepCheckState = new HashSet<Flow_FormContentStepCheckState>();
        }
    
        public string Id { get; set; }
        public string ContentId { get; set; }
        public string StepId { get; set; }
        public int State { get; set; }
        public bool StateFlag { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsEnd { get; set; }
        public bool IsCustom { get; set; }
    
        public virtual Flow_FormContent Flow_FormContent { get; set; }
        public virtual ICollection<Flow_FormContentStepCheckState> Flow_FormContentStepCheckState { get; set; }
    }
}
