//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_Article_Category
    {
        public MIS_Article_Category()
        {
            this.MIS_Article = new HashSet<MIS_Article>();
            this.MIS_Article_Category1 = new HashSet<MIS_Article_Category>();
        }
    
        public string Id { get; set; }
        public Nullable<int> ChannelId { get; set; }
        public string Name { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> Sort { get; set; }
        public string ImgUrl { get; set; }
        public string BodyContent { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public bool Enable { get; set; }
    
        public virtual ICollection<MIS_Article> MIS_Article { get; set; }
        public virtual ICollection<MIS_Article_Category> MIS_Article_Category1 { get; set; }
        public virtual MIS_Article_Category MIS_Article_Category2 { get; set; }
    }
}
