//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_EarlyWareingGood
    {
        public string Id { get; set; }
        public string WareDetailsId { get; set; }
        public decimal LowNumber { get; set; }
        public decimal TotalNumber { get; set; }
        public string ProductType { get; set; }
        public decimal ProductPrice { get; set; }
        public decimal PriceTotal { get; set; }
        public string WarehouseId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Spl_WareDetails Spl_WareDetails { get; set; }
        public virtual Spl_Warehouse Spl_Warehouse { get; set; }
    }
}
