//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_ContactCompany
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string ContactCompanyCategoryId { get; set; }
        public string Remark { get; set; }
        public bool Enable { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Spl_ContactCompanyCategory Spl_ContactCompanyCategory { get; set; }
    }
}
