//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        public SysUser()
        {
            this.SysUserConfig = new HashSet<SysUserConfig>();
            this.SysRole = new HashSet<SysRole>();
            this.MIS_Article = new HashSet<MIS_Article>();
            this.MIS_Article1 = new HashSet<MIS_Article>();
            this.MIS_Article_Comment = new HashSet<MIS_Article_Comment>();
            this.WC_OfficalAccounts = new HashSet<WC_OfficalAccounts>();
            this.SysCalendarPlan = new HashSet<SysCalendarPlan>();
            this.Flow_FormContent = new HashSet<Flow_FormContent>();
            this.Flow_FormContentStepCheckState = new HashSet<Flow_FormContentStepCheckState>();
            this.Flow_Seal = new HashSet<Flow_Seal>();
            this.Spl_WareCheckTotal = new HashSet<Spl_WareCheckTotal>();
            this.Spl_WareCheckTotal1 = new HashSet<Spl_WareCheckTotal>();
            this.Spl_WarehouseAllocation = new HashSet<Spl_WarehouseAllocation>();
            this.Spl_WarehouseWarrant = new HashSet<Spl_WarehouseWarrant>();
            this.Spl_WarehouseWarrantOUT = new HashSet<Spl_WarehouseWarrantOUT>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string TrueName { get; set; }
        public string Card { get; set; }
        public string MobileNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string QQ { get; set; }
        public string EmailAddress { get; set; }
        public string OtherContact { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Village { get; set; }
        public string Address { get; set; }
        public bool State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string Marital { get; set; }
        public string Political { get; set; }
        public string Nationality { get; set; }
        public string Native { get; set; }
        public string School { get; set; }
        public string Professional { get; set; }
        public string Degree { get; set; }
        public string DepId { get; set; }
        public string PosId { get; set; }
        public string Expertise { get; set; }
        public bool JobState { get; set; }
        public string Photo { get; set; }
        public string Attach { get; set; }
        public string Lead { get; set; }
        public string LeadName { get; set; }
        public bool IsSelLead { get; set; }
        public bool IsReportCalendar { get; set; }
        public bool IsSecretary { get; set; }
    
        public virtual ICollection<SysUserConfig> SysUserConfig { get; set; }
        public virtual ICollection<SysRole> SysRole { get; set; }
        public virtual ICollection<MIS_Article> MIS_Article { get; set; }
        public virtual ICollection<MIS_Article> MIS_Article1 { get; set; }
        public virtual ICollection<MIS_Article_Comment> MIS_Article_Comment { get; set; }
        public virtual SysPosition SysPosition { get; set; }
        public virtual SysStruct SysStruct { get; set; }
        public virtual ICollection<WC_OfficalAccounts> WC_OfficalAccounts { get; set; }
        public virtual ICollection<SysCalendarPlan> SysCalendarPlan { get; set; }
        public virtual ICollection<Flow_FormContent> Flow_FormContent { get; set; }
        public virtual ICollection<Flow_FormContentStepCheckState> Flow_FormContentStepCheckState { get; set; }
        public virtual ICollection<Flow_Seal> Flow_Seal { get; set; }
        public virtual ICollection<Spl_WareCheckTotal> Spl_WareCheckTotal { get; set; }
        public virtual ICollection<Spl_WareCheckTotal> Spl_WareCheckTotal1 { get; set; }
        public virtual ICollection<Spl_WarehouseAllocation> Spl_WarehouseAllocation { get; set; }
        public virtual ICollection<Spl_WarehouseWarrant> Spl_WarehouseWarrant { get; set; }
        public virtual ICollection<Spl_WarehouseWarrantOUT> Spl_WarehouseWarrantOUT { get; set; }
    }
}
