//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbForecast
    {
        public string Id { get; set; }
        public string Town { get; set; }
        public string Forecast { get; set; }
        public Nullable<double> Lon { get; set; }
        public Nullable<double> Lat { get; set; }
        public string Wind { get; set; }
        public string Winf { get; set; }
        public Nullable<System.DateTime> YBDatetime { get; set; }
        public Nullable<int> Tmax { get; set; }
        public Nullable<int> Tmin { get; set; }
    
        public virtual tbForecastTerm tbForecastTerm { get; set; }
        public virtual tbWindTerm tbWindTerm { get; set; }
    }
}
