//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WMS_InvHistoryAvg
    {
        public int PartId { get; set; }
        public Nullable<int> InvId { get; set; }
        public string PartCode { get; set; }
        public string PartName { get; set; }
        public string InvCode { get; set; }
        public string InvName { get; set; }
        public Nullable<decimal> Qty { get; set; }
    }
}
