//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_Inventory_H
    {
        public WMS_Inventory_H()
        {
            this.WMS_Inventory_D = new HashSet<WMS_Inventory_D>();
        }
    
        public int Id { get; set; }
        public string InventoryBillNum { get; set; }
        public string InventoryTitle { get; set; }
        public string InventoryPerson { get; set; }
        public Nullable<System.DateTime> InventoryTime { get; set; }
        public string InventoryStatus { get; set; }
        public string InventoryType { get; set; }
        public string Remark { get; set; }
        public string Attr1 { get; set; }
        public string Attr2 { get; set; }
        public string Attr3 { get; set; }
        public string Attr4 { get; set; }
        public string Attr5 { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyPerson { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        public virtual ICollection<WMS_Inventory_D> WMS_Inventory_D { get; set; }
    }
}
