//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_ReturnOrder_D
    {
        public int Id { get; set; }
        public string ReturnOrderDNum { get; set; }
        public int HeadId { get; set; }
        public decimal ReturnQty { get; set; }
        public string Remark { get; set; }
        public string PrintStaus { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string PrintMan { get; set; }
        public string ConfirmStatus { get; set; }
        public string ConfirmMan { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string Attr1 { get; set; }
        public string Attr2 { get; set; }
        public string Attr3 { get; set; }
        public string Attr4 { get; set; }
        public string Attr5 { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyPerson { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> BatchId { get; set; }
        public decimal LossQty { get; set; }
    
        public virtual WMS_ReturnOrder WMS_ReturnOrder { get; set; }
    }
}
