//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2013-04-23 17:16:09 by App
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace Apps.Models.MIS
{

    public partial class MIS_Article_AlbumsModel
    {

        public override string Id { get; set; }
        public override string ArticleId { get; set; }
        public override string BigImg { get; set; }
        public override string SmallImg { get; set; }
        public override string Remark { get; set; }



    }
}

