//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2012-12-11 21:55:13 by App
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace Apps.Models.MIS
{

    public partial class MIS_WebIM_CommonTalkModel
    {
        [Display(Name = "ID")]
        public override string Id { get; set; }
        [Display(Name = "常用语")]
        public override string Talk { get; set; }
        [Display(Name = "状态")]
        public override bool? State { get; set; }
        [DateExpression]//如果填写判断是否是日期
        [Display(Name = "创建时间")]
        public override DateTime? CreateTime { get; set; }


    }
}

