//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Unity.Attributes;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using LinqToExcel;
using System.IO;
using System.Text;
using Apps.IDAL.WMS;
using Apps.Models.WMS;
using Apps.IBLL.WMS;
namespace Apps.BLL.WMS
{
	public partial class WMS_Inv_History_HBLL: Virtual_WMS_Inv_History_HBLL,IWMS_Inv_History_HBLL
	{
        

	}
	public class Virtual_WMS_Inv_History_HBLL
	{
        [Dependency]
        public IWMS_Inv_History_HRepository m_Rep { get; set; }

		public virtual List<WMS_Inv_History_HModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<WMS_Inv_History_H> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								
								a=>a.InvHistoryTitle.Contains(queryStr)
								|| a.Remark.Contains(queryStr)
								|| a.Attr1.Contains(queryStr)
								|| a.Attr2.Contains(queryStr)
								|| a.Attr3.Contains(queryStr)
								|| a.Attr4.Contains(queryStr)
								|| a.Attr5.Contains(queryStr)
								|| a.CreatePerson.Contains(queryStr)
								
								|| a.ModifyPerson.Contains(queryStr)
								
								|| a.InvHistoryStatus.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }

		public virtual List<WMS_Inv_History_HModel> GetListByUserId(ref GridPager pager, string userId,string queryStr)
		{
			return new List<WMS_Inv_History_HModel>();
		}
		
		public virtual List<WMS_Inv_History_HModel> GetListByParentId(ref GridPager pager, string queryStr,object parentId)
        {
			return new List<WMS_Inv_History_HModel>();
		}

        public virtual List<WMS_Inv_History_HModel> CreateModelList(ref IQueryable<WMS_Inv_History_H> queryData)
        {

            List<WMS_Inv_History_HModel> modelList = (from r in queryData
                                              select new WMS_Inv_History_HModel
                                              {
													Id = r.Id,
													InvHistoryTitle = r.InvHistoryTitle,
													Remark = r.Remark,
													Attr1 = r.Attr1,
													Attr2 = r.Attr2,
													Attr3 = r.Attr3,
													Attr4 = r.Attr4,
													Attr5 = r.Attr5,
													CreatePerson = r.CreatePerson,
													CreateTime = r.CreateTime,
													ModifyPerson = r.ModifyPerson,
													ModifyTime = r.ModifyTime,
													InvHistoryStatus = r.InvHistoryStatus,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, WMS_Inv_History_HModel model)
        {
            try
            {
                WMS_Inv_History_H entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new WMS_Inv_History_H();
               				entity.Id = model.Id;
				entity.InvHistoryTitle = model.InvHistoryTitle;
				entity.Remark = model.Remark;
				entity.Attr1 = model.Attr1;
				entity.Attr2 = model.Attr2;
				entity.Attr3 = model.Attr3;
				entity.Attr4 = model.Attr4;
				entity.Attr5 = model.Attr5;
				entity.CreatePerson = model.CreatePerson;
				entity.CreateTime = model.CreateTime;
				entity.ModifyPerson = model.ModifyPerson;
				entity.ModifyTime = model.ModifyTime;
				entity.InvHistoryStatus = model.InvHistoryStatus;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, object id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, object[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, WMS_Inv_History_HModel model)
        {
            try
            {
                WMS_Inv_History_H entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.InvHistoryTitle = model.InvHistoryTitle;
				entity.Remark = model.Remark;
				entity.Attr1 = model.Attr1;
				entity.Attr2 = model.Attr2;
				entity.Attr3 = model.Attr3;
				entity.Attr4 = model.Attr4;
				entity.Attr5 = model.Attr5;
				entity.CreatePerson = model.CreatePerson;
				entity.CreateTime = model.CreateTime;
				entity.ModifyPerson = model.ModifyPerson;
				entity.ModifyTime = model.ModifyTime;
				entity.InvHistoryStatus = model.InvHistoryStatus;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual WMS_Inv_History_HModel GetById(object id)
        {
            if (IsExists(id))
            {
                WMS_Inv_History_H entity = m_Rep.GetById(id);
                WMS_Inv_History_HModel model = new WMS_Inv_History_HModel();
                              				model.Id = entity.Id;
				model.InvHistoryTitle = entity.InvHistoryTitle;
				model.Remark = entity.Remark;
				model.Attr1 = entity.Attr1;
				model.Attr2 = entity.Attr2;
				model.Attr3 = entity.Attr3;
				model.Attr4 = entity.Attr4;
				model.Attr5 = entity.Attr5;
				model.CreatePerson = entity.CreatePerson;
				model.CreateTime = entity.CreateTime;
				model.ModifyPerson = entity.ModifyPerson;
				model.ModifyTime = entity.ModifyTime;
				model.InvHistoryStatus = entity.InvHistoryStatus;
 
                return model;
            }
            else
            {
                return null;
            }
        }


		 /// <summary>
        /// 校验Excel数据,这个方法一般用于重写校验逻辑
        /// </summary>
        public virtual bool CheckImportData(string fileName, List<WMS_Inv_History_HModel> list,ref ValidationErrors errors )
        {
          
            var targetFile = new FileInfo(fileName);

            if (!targetFile.Exists)
            {

                errors.Add("导入的数据文件不存在");
                return false;
            }

            var excelFile = new ExcelQueryFactory(fileName);

            //对应列头
			 				 excelFile.AddMapping<WMS_Inv_History_HModel>(x => x.InvHistoryTitle, "标题");
				 excelFile.AddMapping<WMS_Inv_History_HModel>(x => x.Remark, "备注");
				 excelFile.AddMapping<WMS_Inv_History_HModel>(x => x.Attr1, "Attr1");
				 excelFile.AddMapping<WMS_Inv_History_HModel>(x => x.Attr2, "Attr2");
				 excelFile.AddMapping<WMS_Inv_History_HModel>(x => x.Attr3, "Attr3");
				 excelFile.AddMapping<WMS_Inv_History_HModel>(x => x.Attr4, "Attr4");
				 excelFile.AddMapping<WMS_Inv_History_HModel>(x => x.Attr5, "Attr5");
				 excelFile.AddMapping<WMS_Inv_History_HModel>(x => x.CreatePerson, "创建人");
				 excelFile.AddMapping<WMS_Inv_History_HModel>(x => x.CreateTime, "创建时间");
				 excelFile.AddMapping<WMS_Inv_History_HModel>(x => x.ModifyPerson, "修改人");
				 excelFile.AddMapping<WMS_Inv_History_HModel>(x => x.ModifyTime, "修改时间");
				 excelFile.AddMapping<WMS_Inv_History_HModel>(x => x.InvHistoryStatus, "状态");
 
            //SheetName
            var excelContent = excelFile.Worksheet<WMS_Inv_History_HModel>(0);
            int rowIndex = 1;
            //检查数据正确性
            foreach (var row in excelContent)
            {
                var errorMessage = new StringBuilder();
                var entity = new WMS_Inv_History_HModel();
						 				  entity.Id = row.Id;
				  entity.InvHistoryTitle = row.InvHistoryTitle;
				  entity.Remark = row.Remark;
				  entity.Attr1 = row.Attr1;
				  entity.Attr2 = row.Attr2;
				  entity.Attr3 = row.Attr3;
				  entity.Attr4 = row.Attr4;
				  entity.Attr5 = row.Attr5;
				  entity.CreatePerson = row.CreatePerson;
				  entity.CreateTime = row.CreateTime;
				  entity.ModifyPerson = row.ModifyPerson;
				  entity.ModifyTime = row.ModifyTime;
				  entity.InvHistoryStatus = row.InvHistoryStatus;
 
                //=============================================================================
                if (errorMessage.Length > 0)
                {
                    errors.Add(string.Format(
                        "第 {0} 列发现错误：{1}{2}",
                        rowIndex,
                        errorMessage,
                        "<br/>"));
                }
                list.Add(entity);
                rowIndex += 1;
            }
            if (errors.Count > 0)
            {
                return false;
            }
            return true;
        }

        /// <summary>
        /// 保存数据
        /// </summary>
        public virtual void SaveImportData(IEnumerable<WMS_Inv_History_HModel> list)
        {
            try
            {
                using (DBContainer db = new DBContainer())
                {
                    foreach (var model in list)
                    {
                        WMS_Inv_History_H entity = new WMS_Inv_History_H();
                       						entity.Id = 0;
						entity.InvHistoryTitle = model.InvHistoryTitle;
						entity.Remark = model.Remark;
						entity.Attr1 = model.Attr1;
						entity.Attr2 = model.Attr2;
						entity.Attr3 = model.Attr3;
						entity.Attr4 = model.Attr4;
						entity.Attr5 = model.Attr5;
						entity.CreatePerson = model.CreatePerson;
						entity.CreateTime = ResultHelper.NowTime;
						entity.ModifyPerson = model.ModifyPerson;
						entity.ModifyTime = model.ModifyTime;
						entity.InvHistoryStatus = model.InvHistoryStatus;
 
                        db.WMS_Inv_History_H.Add(entity);
                    }
                    db.SaveChanges();
                }
            }
            catch(Exception ex)
            {
                throw;
            }
        }
		public virtual bool Check(ref ValidationErrors errors, object id,int flag)
        {
			return true;
		}

        public virtual bool IsExists(object id)
        {
            return m_Rep.IsExist(id);
        }
		
		public void Dispose()
        { 
            
        }

	}
}
