//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Unity.Attributes;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using LinqToExcel;
using System.IO;
using System.Text;
using Apps.IDAL.MIS;
using Apps.Models.MIS;
using Apps.IBLL.MIS;
namespace Apps.BLL.MIS
{
	public partial class MIS_WebIM_RecentContactBLL: Virtual_MIS_WebIM_RecentContactBLL,IMIS_WebIM_RecentContactBLL
	{
        

	}
	public class Virtual_MIS_WebIM_RecentContactBLL
	{
        [Dependency]
        public IMIS_WebIM_RecentContactRepository m_Rep { get; set; }

		public virtual List<MIS_WebIM_RecentContactModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<MIS_WebIM_RecentContact> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								
								a=>a.ContactPersons.Contains(queryStr)
								|| a.UserId.Contains(queryStr)
								
								|| a.ContactPersonsTitle.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }

		public virtual List<MIS_WebIM_RecentContactModel> GetListByUserId(ref GridPager pager, string userId,string queryStr)
		{
			return new List<MIS_WebIM_RecentContactModel>();
		}
		
		public virtual List<MIS_WebIM_RecentContactModel> GetListByParentId(ref GridPager pager, string queryStr,object parentId)
        {
			return new List<MIS_WebIM_RecentContactModel>();
		}

        public virtual List<MIS_WebIM_RecentContactModel> CreateModelList(ref IQueryable<MIS_WebIM_RecentContact> queryData)
        {

            List<MIS_WebIM_RecentContactModel> modelList = (from r in queryData
                                              select new MIS_WebIM_RecentContactModel
                                              {
													Id = r.Id,
													ContactPersons = r.ContactPersons,
													UserId = r.UserId,
													InfoTime = r.InfoTime,
													ContactPersonsTitle = r.ContactPersonsTitle,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, MIS_WebIM_RecentContactModel model)
        {
            try
            {
                MIS_WebIM_RecentContact entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new MIS_WebIM_RecentContact();
               				entity.Id = model.Id;
				entity.ContactPersons = model.ContactPersons;
				entity.UserId = model.UserId;
				entity.InfoTime = model.InfoTime;
				entity.ContactPersonsTitle = model.ContactPersonsTitle;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, object id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, object[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, MIS_WebIM_RecentContactModel model)
        {
            try
            {
                MIS_WebIM_RecentContact entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.ContactPersons = model.ContactPersons;
				entity.UserId = model.UserId;
				entity.InfoTime = model.InfoTime;
				entity.ContactPersonsTitle = model.ContactPersonsTitle;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual MIS_WebIM_RecentContactModel GetById(object id)
        {
            if (IsExists(id))
            {
                MIS_WebIM_RecentContact entity = m_Rep.GetById(id);
                MIS_WebIM_RecentContactModel model = new MIS_WebIM_RecentContactModel();
                              				model.Id = entity.Id;
				model.ContactPersons = entity.ContactPersons;
				model.UserId = entity.UserId;
				model.InfoTime = entity.InfoTime;
				model.ContactPersonsTitle = entity.ContactPersonsTitle;
 
                return model;
            }
            else
            {
                return null;
            }
        }


		 /// <summary>
        /// 校验Excel数据,这个方法一般用于重写校验逻辑
        /// </summary>
        public virtual bool CheckImportData(string fileName, List<MIS_WebIM_RecentContactModel> list,ref ValidationErrors errors )
        {
          
            var targetFile = new FileInfo(fileName);

            if (!targetFile.Exists)
            {

                errors.Add("导入的数据文件不存在");
                return false;
            }

            var excelFile = new ExcelQueryFactory(fileName);

            //对应列头
			 				 excelFile.AddMapping<MIS_WebIM_RecentContactModel>(x => x.ContactPersons, "ContactPersons");
				 excelFile.AddMapping<MIS_WebIM_RecentContactModel>(x => x.UserId, "UserId");
				 excelFile.AddMapping<MIS_WebIM_RecentContactModel>(x => x.InfoTime, "InfoTime");
				 excelFile.AddMapping<MIS_WebIM_RecentContactModel>(x => x.ContactPersonsTitle, "ContactPersonsTitle");
 
            //SheetName
            var excelContent = excelFile.Worksheet<MIS_WebIM_RecentContactModel>(0);
            int rowIndex = 1;
            //检查数据正确性
            foreach (var row in excelContent)
            {
                var errorMessage = new StringBuilder();
                var entity = new MIS_WebIM_RecentContactModel();
						 				  entity.Id = row.Id;
				  entity.ContactPersons = row.ContactPersons;
				  entity.UserId = row.UserId;
				  entity.InfoTime = row.InfoTime;
				  entity.ContactPersonsTitle = row.ContactPersonsTitle;
 
                //=============================================================================
                if (errorMessage.Length > 0)
                {
                    errors.Add(string.Format(
                        "第 {0} 列发现错误：{1}{2}",
                        rowIndex,
                        errorMessage,
                        "<br/>"));
                }
                list.Add(entity);
                rowIndex += 1;
            }
            if (errors.Count > 0)
            {
                return false;
            }
            return true;
        }

        /// <summary>
        /// 保存数据
        /// </summary>
        public virtual void SaveImportData(IEnumerable<MIS_WebIM_RecentContactModel> list)
        {
            try
            {
                using (DBContainer db = new DBContainer())
                {
                    foreach (var model in list)
                    {
                        MIS_WebIM_RecentContact entity = new MIS_WebIM_RecentContact();
                       						entity.Id = 0;
						entity.ContactPersons = model.ContactPersons;
						entity.UserId = model.UserId;
						entity.InfoTime = model.InfoTime;
						entity.ContactPersonsTitle = model.ContactPersonsTitle;
 
                        db.MIS_WebIM_RecentContact.Add(entity);
                    }
                    db.SaveChanges();
                }
            }
            catch(Exception ex)
            {
                throw;
            }
        }
		public virtual bool Check(ref ValidationErrors errors, object id,int flag)
        {
			return true;
		}

        public virtual bool IsExists(object id)
        {
            return m_Rep.IsExist(id);
        }
		
		public void Dispose()
        { 
            
        }

	}
}
