//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Unity.Attributes;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using LinqToExcel;
using System.IO;
using System.Text;
using Apps.IDAL.Spl;
using Apps.Models.Spl;
using Apps.IBLL.Spl;
namespace Apps.BLL.Spl
{
	public partial class Spl_WarehouseBLL: Virtual_Spl_WarehouseBLL,ISpl_WarehouseBLL
	{
        

	}
	public class Virtual_Spl_WarehouseBLL
	{
        [Dependency]
        public ISpl_WarehouseRepository m_Rep { get; set; }

		public virtual List<Spl_WarehouseModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<Spl_Warehouse> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.Name.Contains(queryStr)
								|| a.Code.Contains(queryStr)
								
								|| a.ContactPerson.Contains(queryStr)
								|| a.ContactPhone.Contains(queryStr)
								|| a.Address.Contains(queryStr)
								|| a.Remark.Contains(queryStr)
								
								
								|| a.WarehouseCategoryId.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }

		public virtual List<Spl_WarehouseModel> GetListByUserId(ref GridPager pager, string userId,string queryStr)
		{
			return new List<Spl_WarehouseModel>();
		}
		
		public virtual List<Spl_WarehouseModel> GetListByParentId(ref GridPager pager, string queryStr,object parentId)
        {
			return new List<Spl_WarehouseModel>();
		}

        public virtual List<Spl_WarehouseModel> CreateModelList(ref IQueryable<Spl_Warehouse> queryData)
        {

            List<Spl_WarehouseModel> modelList = (from r in queryData
                                              select new Spl_WarehouseModel
                                              {
													Id = r.Id,
													Name = r.Name,
													Code = r.Code,
													IsDefault = r.IsDefault,
													ContactPerson = r.ContactPerson,
													ContactPhone = r.ContactPhone,
													Address = r.Address,
													Remark = r.Remark,
													Enable = r.Enable,
													CreateTime = r.CreateTime,
													WarehouseCategoryId = r.WarehouseCategoryId,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, Spl_WarehouseModel model)
        {
            try
            {
                Spl_Warehouse entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new Spl_Warehouse();
               				entity.Id = model.Id;
				entity.Name = model.Name;
				entity.Code = model.Code;
				entity.IsDefault = model.IsDefault;
				entity.ContactPerson = model.ContactPerson;
				entity.ContactPhone = model.ContactPhone;
				entity.Address = model.Address;
				entity.Remark = model.Remark;
				entity.Enable = model.Enable;
				entity.CreateTime = model.CreateTime;
				entity.WarehouseCategoryId = model.WarehouseCategoryId;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, object id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, object[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, Spl_WarehouseModel model)
        {
            try
            {
                Spl_Warehouse entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.Name = model.Name;
				entity.Code = model.Code;
				entity.IsDefault = model.IsDefault;
				entity.ContactPerson = model.ContactPerson;
				entity.ContactPhone = model.ContactPhone;
				entity.Address = model.Address;
				entity.Remark = model.Remark;
				entity.Enable = model.Enable;
				entity.CreateTime = model.CreateTime;
				entity.WarehouseCategoryId = model.WarehouseCategoryId;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual Spl_WarehouseModel GetById(object id)
        {
            if (IsExists(id))
            {
                Spl_Warehouse entity = m_Rep.GetById(id);
                Spl_WarehouseModel model = new Spl_WarehouseModel();
                              				model.Id = entity.Id;
				model.Name = entity.Name;
				model.Code = entity.Code;
				model.IsDefault = entity.IsDefault;
				model.ContactPerson = entity.ContactPerson;
				model.ContactPhone = entity.ContactPhone;
				model.Address = entity.Address;
				model.Remark = entity.Remark;
				model.Enable = entity.Enable;
				model.CreateTime = entity.CreateTime;
				model.WarehouseCategoryId = entity.WarehouseCategoryId;
 
                return model;
            }
            else
            {
                return null;
            }
        }


		 /// <summary>
        /// 校验Excel数据,这个方法一般用于重写校验逻辑
        /// </summary>
        public virtual bool CheckImportData(string fileName, List<Spl_WarehouseModel> list,ref ValidationErrors errors )
        {
          
            var targetFile = new FileInfo(fileName);

            if (!targetFile.Exists)
            {

                errors.Add("导入的数据文件不存在");
                return false;
            }

            var excelFile = new ExcelQueryFactory(fileName);

            //对应列头
			 				 excelFile.AddMapping<Spl_WarehouseModel>(x => x.Name, "仓库名称");
				 excelFile.AddMapping<Spl_WarehouseModel>(x => x.Code, "仓库编码");
				 excelFile.AddMapping<Spl_WarehouseModel>(x => x.IsDefault, "是否默认");
				 excelFile.AddMapping<Spl_WarehouseModel>(x => x.ContactPerson, "负责人");
				 excelFile.AddMapping<Spl_WarehouseModel>(x => x.ContactPhone, "联系电话");
				 excelFile.AddMapping<Spl_WarehouseModel>(x => x.Address, "地址");
				 excelFile.AddMapping<Spl_WarehouseModel>(x => x.Remark, "备注");
				 excelFile.AddMapping<Spl_WarehouseModel>(x => x.Enable, "状态（true启用，false停用）");
				 excelFile.AddMapping<Spl_WarehouseModel>(x => x.CreateTime, "创建时间");
				 excelFile.AddMapping<Spl_WarehouseModel>(x => x.WarehouseCategoryId, "WarehouseCategoryId");
 
            //SheetName
            var excelContent = excelFile.Worksheet<Spl_WarehouseModel>(0);
            int rowIndex = 1;
            //检查数据正确性
            foreach (var row in excelContent)
            {
                var errorMessage = new StringBuilder();
                var entity = new Spl_WarehouseModel();
						 				  entity.Id = row.Id;
				  entity.Name = row.Name;
				  entity.Code = row.Code;
				  entity.IsDefault = row.IsDefault;
				  entity.ContactPerson = row.ContactPerson;
				  entity.ContactPhone = row.ContactPhone;
				  entity.Address = row.Address;
				  entity.Remark = row.Remark;
				  entity.Enable = row.Enable;
				  entity.CreateTime = row.CreateTime;
				  entity.WarehouseCategoryId = row.WarehouseCategoryId;
 
                //=============================================================================
                if (errorMessage.Length > 0)
                {
                    errors.Add(string.Format(
                        "第 {0} 列发现错误：{1}{2}",
                        rowIndex,
                        errorMessage,
                        "<br/>"));
                }
                list.Add(entity);
                rowIndex += 1;
            }
            if (errors.Count > 0)
            {
                return false;
            }
            return true;
        }

        /// <summary>
        /// 保存数据
        /// </summary>
        public virtual void SaveImportData(IEnumerable<Spl_WarehouseModel> list)
        {
            try
            {
                using (DBContainer db = new DBContainer())
                {
                    foreach (var model in list)
                    {
                        Spl_Warehouse entity = new Spl_Warehouse();
                       						entity.Id = ResultHelper.NewId;
						entity.Name = model.Name;
						entity.Code = model.Code;
						entity.IsDefault = model.IsDefault;
						entity.ContactPerson = model.ContactPerson;
						entity.ContactPhone = model.ContactPhone;
						entity.Address = model.Address;
						entity.Remark = model.Remark;
						entity.Enable = model.Enable;
						entity.CreateTime = ResultHelper.NowTime;
						entity.WarehouseCategoryId = model.WarehouseCategoryId;
 
                        db.Spl_Warehouse.Add(entity);
                    }
                    db.SaveChanges();
                }
            }
            catch(Exception ex)
            {
                throw;
            }
        }
		public virtual bool Check(ref ValidationErrors errors, object id,int flag)
        {
			return true;
		}

        public virtual bool IsExists(object id)
        {
            return m_Rep.IsExist(id);
        }
		
		public void Dispose()
        { 
            
        }

	}
}
