//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Unity.Attributes;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using LinqToExcel;
using System.IO;
using System.Text;
using Apps.IDAL.Sys;
using Apps.Models.Sys;
using Apps.IBLL.Sys;
namespace Apps.BLL.Sys
{
	public partial class SysModuleDataFilterBLL: Virtual_SysModuleDataFilterBLL,ISysModuleDataFilterBLL
	{
        

	}
	public class Virtual_SysModuleDataFilterBLL
	{
        [Dependency]
        public ISysModuleDataFilterRepository m_Rep { get; set; }

		public virtual List<SysModuleDataFilterModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<SysModuleDataFilter> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.Name.Contains(queryStr)
								|| a.KeyCode.Contains(queryStr)
								|| a.ModuleId.Contains(queryStr)
								
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }

		public virtual List<SysModuleDataFilterModel> GetListByUserId(ref GridPager pager, string userId,string queryStr)
		{
			return new List<SysModuleDataFilterModel>();
		}
		
		public virtual List<SysModuleDataFilterModel> GetListByParentId(ref GridPager pager, string queryStr,object parentId)
        {
			return new List<SysModuleDataFilterModel>();
		}

        public virtual List<SysModuleDataFilterModel> CreateModelList(ref IQueryable<SysModuleDataFilter> queryData)
        {

            List<SysModuleDataFilterModel> modelList = (from r in queryData
                                              select new SysModuleDataFilterModel
                                              {
													Id = r.Id,
													Name = r.Name,
													KeyCode = r.KeyCode,
													ModuleId = r.ModuleId,
													IsValid = r.IsValid,
													Sort = r.Sort,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, SysModuleDataFilterModel model)
        {
            try
            {
                SysModuleDataFilter entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new SysModuleDataFilter();
               				entity.Id = model.Id;
				entity.Name = model.Name;
				entity.KeyCode = model.KeyCode;
				entity.ModuleId = model.ModuleId;
				entity.IsValid = model.IsValid;
				entity.Sort = model.Sort;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, object id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, object[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, SysModuleDataFilterModel model)
        {
            try
            {
                SysModuleDataFilter entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.Name = model.Name;
				entity.KeyCode = model.KeyCode;
				entity.ModuleId = model.ModuleId;
				entity.IsValid = model.IsValid;
				entity.Sort = model.Sort;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual SysModuleDataFilterModel GetById(object id)
        {
            if (IsExists(id))
            {
                SysModuleDataFilter entity = m_Rep.GetById(id);
                SysModuleDataFilterModel model = new SysModuleDataFilterModel();
                              				model.Id = entity.Id;
				model.Name = entity.Name;
				model.KeyCode = entity.KeyCode;
				model.ModuleId = entity.ModuleId;
				model.IsValid = entity.IsValid;
				model.Sort = entity.Sort;
 
                return model;
            }
            else
            {
                return null;
            }
        }


		 /// <summary>
        /// 校验Excel数据,这个方法一般用于重写校验逻辑
        /// </summary>
        public virtual bool CheckImportData(string fileName, List<SysModuleDataFilterModel> list,ref ValidationErrors errors )
        {
          
            var targetFile = new FileInfo(fileName);

            if (!targetFile.Exists)
            {

                errors.Add("导入的数据文件不存在");
                return false;
            }

            var excelFile = new ExcelQueryFactory(fileName);

            //对应列头
			 				 excelFile.AddMapping<SysModuleDataFilterModel>(x => x.Name, "字段中文名称");
				 excelFile.AddMapping<SysModuleDataFilterModel>(x => x.KeyCode, "字段");
				 excelFile.AddMapping<SysModuleDataFilterModel>(x => x.ModuleId, "对应模块");
				 excelFile.AddMapping<SysModuleDataFilterModel>(x => x.IsValid, "是否验证（暂时不用）");
				 excelFile.AddMapping<SysModuleDataFilterModel>(x => x.Sort, "排序");
 
            //SheetName
            var excelContent = excelFile.Worksheet<SysModuleDataFilterModel>(0);
            int rowIndex = 1;
            //检查数据正确性
            foreach (var row in excelContent)
            {
                var errorMessage = new StringBuilder();
                var entity = new SysModuleDataFilterModel();
						 				  entity.Id = row.Id;
				  entity.Name = row.Name;
				  entity.KeyCode = row.KeyCode;
				  entity.ModuleId = row.ModuleId;
				  entity.IsValid = row.IsValid;
				  entity.Sort = row.Sort;
 
                //=============================================================================
                if (errorMessage.Length > 0)
                {
                    errors.Add(string.Format(
                        "第 {0} 列发现错误：{1}{2}",
                        rowIndex,
                        errorMessage,
                        "<br/>"));
                }
                list.Add(entity);
                rowIndex += 1;
            }
            if (errors.Count > 0)
            {
                return false;
            }
            return true;
        }

        /// <summary>
        /// 保存数据
        /// </summary>
        public virtual void SaveImportData(IEnumerable<SysModuleDataFilterModel> list)
        {
            try
            {
                using (DBContainer db = new DBContainer())
                {
                    foreach (var model in list)
                    {
                        SysModuleDataFilter entity = new SysModuleDataFilter();
                       						entity.Id = ResultHelper.NewId;
						entity.Name = model.Name;
						entity.KeyCode = model.KeyCode;
						entity.ModuleId = model.ModuleId;
						entity.IsValid = model.IsValid;
						entity.Sort = model.Sort;
 
                        db.SysModuleDataFilter.Add(entity);
                    }
                    db.SaveChanges();
                }
            }
            catch(Exception ex)
            {
                throw;
            }
        }
		public virtual bool Check(ref ValidationErrors errors, object id,int flag)
        {
			return true;
		}

        public virtual bool IsExists(object id)
        {
            return m_Rep.IsExist(id);
        }
		
		public void Dispose()
        { 
            
        }

	}
}
