//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Unity.Attributes;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using LinqToExcel;
using System.IO;
using System.Text;
using Apps.IDAL.Flow;
using Apps.Models.Flow;
using Apps.IBLL.Flow;
namespace Apps.BLL.Flow
{
	public partial class Flow_StepRuleBLL: Virtual_Flow_StepRuleBLL,IFlow_StepRuleBLL
	{
        

	}
	public class Virtual_Flow_StepRuleBLL
	{
        [Dependency]
        public IFlow_StepRuleRepository m_Rep { get; set; }

		public virtual List<Flow_StepRuleModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<Flow_StepRule> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.StepId.Contains(queryStr)
								|| a.AttrId.Contains(queryStr)
								|| a.Operator.Contains(queryStr)
								|| a.Result.Contains(queryStr)
								|| a.NextStep.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }

		public virtual List<Flow_StepRuleModel> GetListByUserId(ref GridPager pager, string userId,string queryStr)
		{
			return new List<Flow_StepRuleModel>();
		}
		
		public virtual List<Flow_StepRuleModel> GetListByParentId(ref GridPager pager, string queryStr,object parentId)
        {
			return new List<Flow_StepRuleModel>();
		}

        public virtual List<Flow_StepRuleModel> CreateModelList(ref IQueryable<Flow_StepRule> queryData)
        {

            List<Flow_StepRuleModel> modelList = (from r in queryData
                                              select new Flow_StepRuleModel
                                              {
													Id = r.Id,
													StepId = r.StepId,
													AttrId = r.AttrId,
													Operator = r.Operator,
													Result = r.Result,
													NextStep = r.NextStep,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, Flow_StepRuleModel model)
        {
            try
            {
                Flow_StepRule entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new Flow_StepRule();
               				entity.Id = model.Id;
				entity.StepId = model.StepId;
				entity.AttrId = model.AttrId;
				entity.Operator = model.Operator;
				entity.Result = model.Result;
				entity.NextStep = model.NextStep;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, object id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, object[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, Flow_StepRuleModel model)
        {
            try
            {
                Flow_StepRule entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.StepId = model.StepId;
				entity.AttrId = model.AttrId;
				entity.Operator = model.Operator;
				entity.Result = model.Result;
				entity.NextStep = model.NextStep;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual Flow_StepRuleModel GetById(object id)
        {
            if (IsExists(id))
            {
                Flow_StepRule entity = m_Rep.GetById(id);
                Flow_StepRuleModel model = new Flow_StepRuleModel();
                              				model.Id = entity.Id;
				model.StepId = entity.StepId;
				model.AttrId = entity.AttrId;
				model.Operator = entity.Operator;
				model.Result = entity.Result;
				model.NextStep = entity.NextStep;
 
                return model;
            }
            else
            {
                return null;
            }
        }


		 /// <summary>
        /// 校验Excel数据,这个方法一般用于重写校验逻辑
        /// </summary>
        public virtual bool CheckImportData(string fileName, List<Flow_StepRuleModel> list,ref ValidationErrors errors )
        {
          
            var targetFile = new FileInfo(fileName);

            if (!targetFile.Exists)
            {

                errors.Add("导入的数据文件不存在");
                return false;
            }

            var excelFile = new ExcelQueryFactory(fileName);

            //对应列头
			 				 excelFile.AddMapping<Flow_StepRuleModel>(x => x.StepId, "StepId");
				 excelFile.AddMapping<Flow_StepRuleModel>(x => x.AttrId, "AttrId");
				 excelFile.AddMapping<Flow_StepRuleModel>(x => x.Operator, "Operator");
				 excelFile.AddMapping<Flow_StepRuleModel>(x => x.Result, "Result");
				 excelFile.AddMapping<Flow_StepRuleModel>(x => x.NextStep, "NextStep");
 
            //SheetName
            var excelContent = excelFile.Worksheet<Flow_StepRuleModel>(0);
            int rowIndex = 1;
            //检查数据正确性
            foreach (var row in excelContent)
            {
                var errorMessage = new StringBuilder();
                var entity = new Flow_StepRuleModel();
						 				  entity.Id = row.Id;
				  entity.StepId = row.StepId;
				  entity.AttrId = row.AttrId;
				  entity.Operator = row.Operator;
				  entity.Result = row.Result;
				  entity.NextStep = row.NextStep;
 
                //=============================================================================
                if (errorMessage.Length > 0)
                {
                    errors.Add(string.Format(
                        "第 {0} 列发现错误：{1}{2}",
                        rowIndex,
                        errorMessage,
                        "<br/>"));
                }
                list.Add(entity);
                rowIndex += 1;
            }
            if (errors.Count > 0)
            {
                return false;
            }
            return true;
        }

        /// <summary>
        /// 保存数据
        /// </summary>
        public virtual void SaveImportData(IEnumerable<Flow_StepRuleModel> list)
        {
            try
            {
                using (DBContainer db = new DBContainer())
                {
                    foreach (var model in list)
                    {
                        Flow_StepRule entity = new Flow_StepRule();
                       						entity.Id = ResultHelper.NewId;
						entity.StepId = model.StepId;
						entity.AttrId = model.AttrId;
						entity.Operator = model.Operator;
						entity.Result = model.Result;
						entity.NextStep = model.NextStep;
 
                        db.Flow_StepRule.Add(entity);
                    }
                    db.SaveChanges();
                }
            }
            catch(Exception ex)
            {
                throw;
            }
        }
		public virtual bool Check(ref ValidationErrors errors, object id,int flag)
        {
			return true;
		}

        public virtual bool IsExists(object id)
        {
            return m_Rep.IsExist(id);
        }
		
		public void Dispose()
        { 
            
        }

	}
}
