//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Apps.Common;
using System.Collections.Generic;
using Apps.Models.Spl;
using Apps.Models;

namespace Apps.IBLL.Spl
{
    public partial interface ISpl_WarehouseWarrantBLL
    {
        List<Spl_WarehouseWarrantModel> GetList(ref GridPager pager, string queryStr, string sysUserId);
        void SaveData(IEnumerable<Spl_WarehouseWarrantDetailsModel> personList);
        void SaveEditData(IEnumerable<Spl_WarehouseWarrantDetailsModel> personList, string warehouseWarrantId);
        bool Check(ref ValidationErrors errors, string id, int checkFlag, string checker);

        //  bool edit(ref ValidationErrors errors, string id);
        List<Spl_WareInReportModel> GetWareInList(string warehouseId, DateTime begin, DateTime end);

    }
}
