//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.Models.Flow;
using Apps.IDAL.Flow;
using System;
namespace Apps.DAL.Flow
{
	public partial class Flow_StepRepository:BaseRepository<Flow_Step>,IFlow_StepRepository,IDisposable
	{
	    public Flow_StepRepository(DBContainer db):base(db)
        {
        
        }
	}
}
