//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.Models.JOB;
using Apps.IDAL.JOB;
using System;
namespace Apps.DAL.JOB
{
	public partial class JOB_TASKJOBS_LOGRepository:BaseRepository<JOB_TASKJOBS_LOG>,IJOB_TASKJOBS_LOGRepository,IDisposable
	{
	    public JOB_TASKJOBS_LOGRepository(DBContainer db):base(db)
        {
        
        }
	}
}
