//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.Models.Spl;
using Apps.IDAL.Spl;
using System;
namespace Apps.DAL.Spl
{
	public partial class Spl_WarehouseCategoryRepository:BaseRepository<Spl_WarehouseCategory>,ISpl_WarehouseCategoryRepository,IDisposable
	{
	    public Spl_WarehouseCategoryRepository(DBContainer db):base(db)
        {
        
        }
	}
}
