//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.Models.WMS;
using Apps.IDAL.WMS;
using System;
namespace Apps.DAL.WMS
{
	public partial class WMS_SubInvInfoRepository:BaseRepository<WMS_SubInvInfo>,IWMS_SubInvInfoRepository,IDisposable
	{
	    public WMS_SubInvInfoRepository(DBContainer db):base(db)
        {
        
        }
	}
}
