//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2013-04-23 17:16:17 by App
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System.Linq;
namespace Apps.IDAL.MIS
{
    public partial interface IMIS_Article_AlbumsRepository
    {
     

    }
}



