//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysModuleOperateModel:Virtual_SysModuleOperateModel
	{
		
	}
	public class Virtual_SysModuleOperateModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "操作名称")]
		public virtual string Name { get; set; }
		[Display(Name = "操作码")]
		public virtual string KeyCode { get; set; }
		[Display(Name = "对应模块")]
		public virtual string ModuleId { get; set; }
		[Display(Name = "是否验证")]
		public virtual bool IsValid { get; set; }
		[Display(Name = "排序")]
		public virtual int Sort { get; set; }
		}
}
