//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.WMS
{

	public partial class WMS_Inventory_HModel:Virtual_WMS_Inventory_HModel
	{
		
	}
	public class Virtual_WMS_Inventory_HModel
	{
		[Display(Name = "未设置")]
		public virtual int Id { get; set; }
		[Display(Name = "盘点单据号")]
		public virtual string InventoryBillNum { get; set; }
		[Display(Name = "盘点标题")]
		public virtual string InventoryTitle { get; set; }
		[Display(Name = "盘点人")]
		public virtual string InventoryPerson { get; set; }
		[Display(Name = "盘点时间")]
		public virtual Nullable<System.DateTime> InventoryTime { get; set; }
		[Display(Name = "盘点状态")]
		public virtual string InventoryStatus { get; set; }
		[Display(Name = "盘点类型")]
		public virtual string InventoryType { get; set; }
		[Display(Name = "未设置")]
		public virtual string Remark { get; set; }
		[Display(Name = "未设置")]
		public virtual string Attr1 { get; set; }
		[Display(Name = "未设置")]
		public virtual string Attr2 { get; set; }
		[Display(Name = "未设置")]
		public virtual string Attr3 { get; set; }
		[Display(Name = "未设置")]
		public virtual string Attr4 { get; set; }
		[Display(Name = "未设置")]
		public virtual string Attr5 { get; set; }
		[Display(Name = "创建人")]
		public virtual string CreatePerson { get; set; }
		[Display(Name = "创建时间")]
		public virtual Nullable<System.DateTime> CreateTime { get; set; }
		[Display(Name = "修改人")]
		public virtual string ModifyPerson { get; set; }
		[Display(Name = "修改时间")]
		public virtual Nullable<System.DateTime> ModifyTime { get; set; }
		}
}
