//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysParamModel:Virtual_SysParamModel
	{
		
	}
	public class Virtual_SysParamModel
	{
		[Display(Name = "未设置")]
		public virtual int Id { get; set; }
		[Display(Name = "参数类别编码")]
		public virtual string TypeCode { get; set; }
		[Display(Name = "参数类别名称")]
		public virtual string TypeName { get; set; }
		[Display(Name = "参数值编码")]
		public virtual string ParamCode { get; set; }
		[Display(Name = "参数值名称")]
		public virtual string ParamName { get; set; }
		[Display(Name = "创建人")]
		public virtual string CreatePerson { get; set; }
		[Display(Name = "创建时间")]
		public virtual Nullable<System.DateTime> CreateTime { get; set; }
		[Display(Name = "修改人")]
		public virtual string ModifyPerson { get; set; }
		[Display(Name = "修改时间")]
		public virtual Nullable<System.DateTime> ModifyTime { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<int> Sort { get; set; }
		[Display(Name = "未设置")]
		public virtual bool Enable { get; set; }
		}
}
