//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Spl
{

	public partial class Spl_WareCheckTotalModel:Virtual_Spl_WareCheckTotalModel
	{
		
	}
	public class Virtual_Spl_WareCheckTotalModel
	{
		[Display(Name = "单号")]
		public virtual string Id { get; set; }
		[Display(Name = "货品名称")]
		public virtual string WareDetailsId { get; set; }
		[Display(Name = "所属仓库")]
		public virtual string WarehouseId { get; set; }
		[Display(Name = "盘点说明")]
		public virtual string Remark { get; set; }
		[Display(Name = "实际总数")]
		public virtual decimal DiffQuantity { get; set; }
		[Display(Name = "原有总数")]
		public virtual decimal Quantity { get; set; }
		[Display(Name = "单价")]
		public virtual decimal Price { get; set; }
		[Display(Name = "审核状态")]
		public virtual int State { get; set; }
		[Display(Name = "创建人")]
		public virtual string Creater { get; set; }
		[Display(Name = "审核人")]
		public virtual string Checker { get; set; }
		[Display(Name = "审核时间")]
		public virtual Nullable<System.DateTime> CheckTime { get; set; }
		[Display(Name = "是否确认")]
		public virtual bool Confirmation { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		}
}
