//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Spl
{

	public partial class Spl_WarehouseAllocationDetailsModel:Virtual_Spl_WarehouseAllocationDetailsModel
	{
		
	}
	public class Virtual_Spl_WarehouseAllocationDetailsModel
	{
		[Display(Name = "未设置")]
		public virtual string Id { get; set; }
		[Display(Name = "未设置")]
		public virtual string WareDetailsId { get; set; }
		[Display(Name = "未设置")]
		public virtual string WarehouseId { get; set; }
		[Display(Name = "未设置")]
		public virtual string WarehouseAllocationId { get; set; }
		[Display(Name = "未设置")]
		public virtual decimal Quantity { get; set; }
		[Display(Name = "未设置")]
		public virtual decimal Price { get; set; }
		[Display(Name = "未设置")]
		public virtual decimal TotalPrice { get; set; }
		[Display(Name = "未设置")]
		public virtual string Defined { get; set; }
		[Display(Name = "未设置")]
		public virtual System.DateTime CreateTime { get; set; }
		}
}
