//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Flow
{

	public partial class Flow_FormAttrModel:Virtual_Flow_FormAttrModel
	{
		
	}
	public class Virtual_Flow_FormAttrModel
	{
		[Display(Name = "ID")]
		public virtual string Id { get; set; }
		[Display(Name = "字段标题")]
		public virtual string Title { get; set; }
		[Display(Name = "字段英文名称")]
		public virtual string Name { get; set; }
		[Display(Name = "文本,日期,数字,多行文本")]
		public virtual string AttrType { get; set; }
		[Display(Name = "校验规则")]
		public virtual string CheckRule { get; set; }
		[Display(Name = "辅助JS脚本")]
		public virtual string CheckJS { get; set; }
		[Display(Name = "所属类别")]
		public virtual string TypeId { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		[Display(Name = "下拉框的值")]
		public virtual string OptionList { get; set; }
		}
}
