//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Flow
{

	public partial class Flow_FormModel:Virtual_Flow_FormModel
	{
		
	}
	public class Virtual_Flow_FormModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "表单名称")]
		public virtual string Name { get; set; }
		[Display(Name = "表单说明")]
		public virtual string Remark { get; set; }
		[Display(Name = "使用部门")]
		public virtual string UsingDep { get; set; }
		[Display(Name = "所属类别")]
		public virtual string TypeId { get; set; }
		[Display(Name = "是否完成流程")]
		public virtual bool State { get; set; }
		[Display(Name = "创建时间")]
		public virtual Nullable<System.DateTime> CreateTime { get; set; }
		[Display(Name = "自由布局")]
		public virtual string HtmlForm { get; set; }
		[Display(Name = "表单来源")]
		public virtual bool IsExternal { get; set; }
		[Display(Name = "是否外部来源")]
		public virtual string ExternalURL { get; set; }
		[Display(Name = "字段A")]
		public virtual string AttrA { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrB { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrC { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrD { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrE { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrF { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrG { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrH { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrI { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrJ { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrK { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrL { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrM { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrN { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrO { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrP { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrQ { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrR { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrS { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrT { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrU { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrV { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrW { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrX { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrY { get; set; }
		[Display(Name = "未设置")]
		public virtual string AttrZ { get; set; }
		}
}
