//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.V
{

	public partial class V_WMS_InvHistoryAvgModel:Virtual_V_WMS_InvHistoryAvgModel
	{
		
	}
	public class Virtual_V_WMS_InvHistoryAvgModel
	{
		[Display(Name = "未设置")]
		public virtual Nullable<long> Id { get; set; }
		[Display(Name = "未设置")]
		public virtual int PartId { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<int> InvId { get; set; }
		[Display(Name = "未设置")]
		public virtual string PartCode { get; set; }
		[Display(Name = "未设置")]
		public virtual string PartName { get; set; }
		[Display(Name = "未设置")]
		public virtual string InvCode { get; set; }
		[Display(Name = "未设置")]
		public virtual string InvName { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<decimal> AvgQty { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<decimal> InvQty { get; set; }
		}
}
