//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.WMS
{

	public partial class WMS_HeaderModel:Virtual_WMS_HeaderModel
	{
		
	}
	public class Virtual_WMS_HeaderModel
	{
		[Display(Name = "未设置")]
		public virtual int Id { get; set; }
		[Display(Name = "未设置")]
		public virtual string Code { get; set; }
		[Display(Name = "未设置")]
		public virtual string Name { get; set; }
		}
}
