//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Spl
{

	public partial class Spl_WareDetailsModel:Virtual_Spl_WareDetailsModel
	{
		
	}
	public class Virtual_Spl_WareDetailsModel
	{
		[Display(Name = "主键ID")]
		public virtual string Id { get; set; }
		[Display(Name = "名称")]
		public virtual string Name { get; set; }
		[Display(Name = "编码")]
		public virtual string Code { get; set; }
		[Display(Name = "条码")]
		public virtual string BarCode { get; set; }
		[Display(Name = "存货分类")]
		public virtual string WareCategoryId { get; set; }
		[Display(Name = "计量单位")]
		public virtual string Unit { get; set; }
		[Display(Name = "存货标签")]
		public virtual string Lable { get; set; }
		[Display(Name = "参考进价")]
		public virtual Nullable<decimal> BuyPrice { get; set; }
		[Display(Name = "参考售价")]
		public virtual decimal SalePrice { get; set; }
		[Display(Name = "零售价")]
		public virtual Nullable<decimal> RetailPrice { get; set; }
		[Display(Name = "备注")]
		public virtual string Remark { get; set; }
		[Display(Name = "其他信息-厂家")]
		public virtual string Vender { get; set; }
		[Display(Name = "品牌")]
		public virtual string Brand { get; set; }
		[Display(Name = "颜色")]
		public virtual string Color { get; set; }
		[Display(Name = "材质")]
		public virtual string Material { get; set; }
		[Display(Name = "尺码")]
		public virtual string Size { get; set; }
		[Display(Name = "重量")]
		public virtual string Weight { get; set; }
		[Display(Name = "产地")]
		public virtual string ComeFrom { get; set; }
		[Display(Name = "最高库存")]
		public virtual Nullable<decimal> UpperLimit { get; set; }
		[Display(Name = "最低库存")]
		public virtual Nullable<decimal> LowerLimit { get; set; }
		[Display(Name = "参考成本")]
		public virtual Nullable<decimal> PrimeCost { get; set; }
		[Display(Name = "一级价格")]
		public virtual Nullable<decimal> Price1 { get; set; }
		[Display(Name = "二级价格")]
		public virtual Nullable<decimal> Price2 { get; set; }
		[Display(Name = "三级价格")]
		public virtual Nullable<decimal> Price3 { get; set; }
		[Display(Name = "四级价格")]
		public virtual Nullable<decimal> Price4 { get; set; }
		[Display(Name = "五级价格")]
		public virtual Nullable<decimal> Price5 { get; set; }
		[Display(Name = "照片1")]
		public virtual string Photo1 { get; set; }
		[Display(Name = "照片2")]
		public virtual string Photo2 { get; set; }
		[Display(Name = "照片3")]
		public virtual string Photo3 { get; set; }
		[Display(Name = "照片4")]
		public virtual string Photo4 { get; set; }
		[Display(Name = "照片5")]
		public virtual string Photo5 { get; set; }
		[Display(Name = "状态")]
		public virtual bool Enable { get; set; }
		[Display(Name = "未设置")]
		public virtual System.DateTime CreateTime { get; set; }
		}
}
