//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.WC
{

	public partial class WC_MessageResponseModel:Virtual_WC_MessageResponseModel
	{
		
	}
	public class Virtual_WC_MessageResponseModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "所属公众号")]
		public virtual string OfficalAccountId { get; set; }
		[Display(Name = "消息规则")]
		public virtual Nullable<int> MessageRule { get; set; }
		[Display(Name = "触发类型")]
		public virtual Nullable<int> Category { get; set; }
		[Display(Name = "关键字")]
		public virtual string MatchKey { get; set; }
		[Display(Name = "文本内容")]
		public virtual string TextContent { get; set; }
		[Display(Name = "图文文本内容")]
		public virtual string ImgTextContext { get; set; }
		[Display(Name = "图文图片URL")]
		public virtual string ImgTextUrl { get; set; }
		[Display(Name = "图文跳转")]
		public virtual string ImgTextLink { get; set; }
		[Display(Name = "语言URL")]
		public virtual string MeidaUrl { get; set; }
		[Display(Name = "语音跳转")]
		public virtual string MeidaLink { get; set; }
		[Display(Name = "是否启用")]
		public virtual bool Enable { get; set; }
		[Display(Name = "是否默认（在默认回复和关注时候回复开启）")]
		public virtual bool IsDefault { get; set; }
		[Display(Name = "说明")]
		public virtual string Remark { get; set; }
		[Display(Name = "排序")]
		public virtual int Sort { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		[Display(Name = "创建人")]
		public virtual string CreateBy { get; set; }
		[Display(Name = "修改时间")]
		public virtual System.DateTime ModifyTime { get; set; }
		[Display(Name = "修改人")]
		public virtual string ModifyBy { get; set; }
		}
}
