//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Sys
{

	public partial class SysSequenceModel:Virtual_SysSequenceModel
	{
		
	}
	public class Virtual_SysSequenceModel
	{
		[Display(Name = "序号")]
		public virtual int Id { get; set; }
		[Display(Name = "未设置")]
		public virtual string SN { get; set; }
		[Display(Name = "表名")]
		public virtual string TabName { get; set; }
		[Display(Name = "类型1")]
		public virtual int FirstType { get; set; }
		[Display(Name = "规则1")]
		public virtual string FirstRule { get; set; }
		[Display(Name = "长度1")]
		public virtual Nullable<int> FirstLength { get; set; }
		[Display(Name = "类型2")]
		public virtual Nullable<int> SecondType { get; set; }
		[Display(Name = "规则2")]
		public virtual string SecondRule { get; set; }
		[Display(Name = "长度2")]
		public virtual Nullable<int> SecondLength { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<int> ThirdType { get; set; }
		[Display(Name = "未设置")]
		public virtual string ThirdRule { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<int> ThirdLength { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<int> FourType { get; set; }
		[Display(Name = "未设置")]
		public virtual string FourRule { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<int> FourLength { get; set; }
		[Display(Name = "连接符")]
		public virtual string JoinChar { get; set; }
		[Display(Name = "未设置")]
		public virtual string Sample { get; set; }
		[Display(Name = "未设置")]
		public virtual string CurrentValue { get; set; }
		[Display(Name = "备注")]
		public virtual string Remark { get; set; }
		}
}
