//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.Spl
{

	public partial class Spl_ContactCompanyModel:Virtual_Spl_ContactCompanyModel
	{
		
	}
	public class Virtual_Spl_ContactCompanyModel
	{
		[Display(Name = "主键ID")]
		public virtual string Id { get; set; }
		[Display(Name = "编码")]
		public virtual string Code { get; set; }
		[Display(Name = "来往单位")]
		public virtual string Name { get; set; }
		[Display(Name = "联系电话")]
		public virtual string Phone { get; set; }
		[Display(Name = "单位类别")]
		public virtual string ContactCompanyCategoryId { get; set; }
		[Display(Name = "未设置")]
		public virtual string Remark { get; set; }
		[Display(Name = "是否启用")]
		public virtual bool Enable { get; set; }
		[Display(Name = "创建时间")]
		public virtual System.DateTime CreateTime { get; set; }
		}
}
