//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.MIS
{

	public partial class MIS_WebIM_RecentContactModel:Virtual_MIS_WebIM_RecentContactModel
	{
		
	}
	public class Virtual_MIS_WebIM_RecentContactModel
	{
		[Display(Name = "未设置")]
		public virtual int Id { get; set; }
		[Display(Name = "以代码显示")]
		public virtual string ContactPersons { get; set; }
		[Display(Name = "未设置")]
		public virtual string UserId { get; set; }
		[Display(Name = "未设置")]
		public virtual System.DateTime InfoTime { get; set; }
		[Display(Name = "以名称显示")]
		public virtual string ContactPersonsTitle { get; set; }
		}
}
