//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.MIS
{

	public partial class MIS_WebIM_MessageModel:Virtual_MIS_WebIM_MessageModel
	{
		
	}
	public class Virtual_MIS_WebIM_MessageModel
	{
		[Display(Name = "未设置")]
		public virtual string Id { get; set; }
		[Display(Name = "未设置")]
		public virtual string Message { get; set; }
		[Display(Name = "未设置")]
		public virtual string Sender { get; set; }
		[Display(Name = "以代码显示")]
		public virtual string receiver { get; set; }
		[Display(Name = "即时=0，推迟=1")]
		public virtual bool State { get; set; }
		[Display(Name = "未设置")]
		public virtual Nullable<System.DateTime> SendDt { get; set; }
		[Display(Name = "以名称显示")]
		public virtual string receiverTitle { get; set; }
		}
}
