//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.WMS
{

	public partial class WMS_SupplierModel:Virtual_WMS_SupplierModel
	{
		
	}
	public class Virtual_WMS_SupplierModel
	{
		[Display(Name = "供应商ID")]
		public virtual int Id { get; set; }
		[Display(Name = "供应商编码")]
		public virtual string SupplierCode { get; set; }
		[Display(Name = "供应商简称")]
		public virtual string SupplierShortName { get; set; }
		[Display(Name = "供应商名称")]
		public virtual string SupplierName { get; set; }
		[Display(Name = "供应商类型")]
		public virtual string SupplierType { get; set; }
		[Display(Name = "联系人")]
		public virtual string LinkMan { get; set; }
		[Display(Name = "联系人电话")]
		public virtual string LinkManTel { get; set; }
		[Display(Name = "联系人地址")]
		public virtual string LinkManAddress { get; set; }
		[Display(Name = "状态")]
		public virtual string Status { get; set; }
		[Display(Name = "说明")]
		public virtual string Remark { get; set; }
		[Display(Name = "创建人")]
		public virtual string CreatePerson { get; set; }
		[Display(Name = "创建时间")]
		public virtual Nullable<System.DateTime> CreateTime { get; set; }
		[Display(Name = "修改人")]
		public virtual string ModifyPerson { get; set; }
		[Display(Name = "修改时间")]
		public virtual Nullable<System.DateTime> ModifyTime { get; set; }
		}
}
