//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.ComponentModel.DataAnnotations;
namespace Apps.Models.WC
{

	public partial class WC_GroupModel:Virtual_WC_GroupModel
	{
		
	}
	public class Virtual_WC_GroupModel
	{
		[Display(Name = "GUID主键")]
		public virtual string Id { get; set; }
		[Display(Name = "组别")]
		public virtual string Name { get; set; }
		[Display(Name = "合计")]
		public virtual int Count { get; set; }
		[Display(Name = "所属公众号")]
		public virtual string OfficalAccountId { get; set; }
		}
}
