//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Apps.Common;
using System.Collections.Generic;
using Apps.Models.WMS;
namespace Apps.IBLL.WMS
{
	public partial interface IWMS_Inv_History_HBLL:IBaseBLL<WMS_Inv_History_HModel>
	{
      
	}
}
